### ISSUE TITLE
Flickering preceding screen melt effect 

### ISSUE THREAD

**Issue by 01y** [fgsfdsfgs/prboom-plus#5]
Extra draws visible when starting a new game, exiting a level, etc.

**Comment by fgsfdsfgs** [comment]
That's because the way this works in the Vita port is it has to update the framebuffer with the "target" frame first, and since it renders to one framebuffer which also shows up on the screen, you can see that frame before the wipe starts. I'll look into rendering that into an off-screen framebuffer.

**Comment by fgsfdsfgs** [comment]
Should be fixed in adec853.
